### ISSUE TITLE
Skype critical error at loading

### ISSUE THREAD

**Issue by nestdimon** [dlehn/Skype-Utility-Project#13] opened 2015-02-25 10:10 UTC
Skype was updated to the 7.1.0.105 version and after restart it crash with critical error. The only way to run it, is to rename SUP's "dxd9.dll" to something other. Does somebody have the same problem?

**Comment by dlehn** [comment] 2015-02-25 18:50
See issue #12, simply reapplying the update/reinstalling Skype might help.

**Comment by nestdimon** [comment] 2015-02-26 09:35
Nope, it doesn't. 
I gid it and found that if "Hide identity panel" is checked than Skype crashes at startup. If not checked, than all works fine.

**Comment by dlehn** [comment] 2015-02-26 12:28
Well that is interesting... finally a bug I can at least kind of reproduce.  
If I check that option, Skype gets stuck with the "offline" icon being displayed in the system tray and then freezes (although it doesn't crash for me).  
I'll look into it right away.

**Comment by dlehn** [comment] 2015-02-26 13:16
Issue should be fixed now in version [1.3.5](https://github.com/dlehn/Skype-Utility-Project/releases/tag/1.3.5) (see a1b91c0c4e2054802d8f635f0c2a9b0165c64329). 
(At least it works for me, please reopen this issue if you're still having trouble.)

**Closed as completed by dlehn** 2015-02-26 13:16 UTC
